name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check server health
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.DEPLOYED_URL }}
          max-attempts: 3
          retry-delay: 10s
          follow-redirect: true

      - name: Notify failure in Discord
        if: failure()
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: "❌ Health check failed for `${{ secrets.DEPLOYED_URL }}`"
