name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e

      - name: Discord Notification Success
        if: ${{ success() }}
        uses: Ilshidur/action-discord@v0.3.2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "✅ Build & tests succeeded for commit `${{ github.sha }}`"
          username: "GitHub Actions"

      - name: Discord Notification Failure
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@v0.3.2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            ❌ Build or tests failed for commit `${{ github.sha }}`
            Repository: `${{ github.repository }}`
            Workflow: `${{ github.workflow }}`
          username: "GitHub Actions"

  deploy_to_render:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false

  tag_release:
    needs: deploy_to_render
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: false
      - name: Discord Notification Success
        if: ${{ success() }}
        uses: Ilshidur/action-discord@v0.3.2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "✅ Deployment and tagging succeeded for commit `${{ github.sha }}`"
          username: "GitHub Actions"
      - name: Discord Notification Failure
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@v0.3.2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            ❌ Deployment or tagging failed for commit `${{ github.sha }}`
            Repository: `${{ github.repository }}`
            Workflow: `${{ github.workflow }}`
          username: "GitHub Actions"
